# Initialization
/run/initialize

# Visualisation
/vis/open OGLI
/vis/viewer/set/autoRefresh false
/vis/drawVolume
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate 100  # Limit accumulation to 10 events
/vis/viewer/set/viewpointThetaPhi 45 45 deg
/vis/viewer/set/style wireframe
/vis/viewer/set/autoRefresh true

# Progress tracking
/run/printProgress 5

# Verbosity
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
