[detector]
world_half_size = 4000         ## mm
world_material = "G4_Galactic"

hz = 3800

inner_chamber_radius = 500


[detector.tracker]
enabled = true

magnetic_field_strength = 2.0
layer_count = 10

active_width = 0.2   # Silicon scintillator
passive_width = 14.8 # Galatic Air

active_material = "G4_Si"
passive_material = "G4_Galactic"

[detector.gap1]
enabled = true

width = 350

[detector.ecal]
enabled = true

layer_count = 60

passive_width = 2.5
active_width = 2.0

passive_material = "G4_Pb"
active_material = "G4_POLYSTYRENE"

[detector.gap2]
enabled = true

width = 500

[detector.hcal]
enabled = true

layer_count = 96

passive_width = 14.0 # Iron absorber
active_width = 2.0   # Polystyrene scintillator

active_material = "G4_POLYSTYRENE"
passive_material = "G4_Fe"
