name: HEP Pipeline Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: hep-pipeline
          environment-file: environment.yml
          use-mamba: true

      - name: Configure CMake
        shell: bash -l {0}
        run: cmake -B build -S .

      - name: Build Project
        shell: bash -l {0}
        run: cmake --build build

      - name: Verify Binaries
        shell: bash -l {0}
        run: |
          if [ -f "./build/event-generation/gen_events" ]; then
            echo "Executable gen_events successfully built."
          else
            echo "Executable gen_events not found!"
            exit 1
          fi
